---
title: "Prjet RP - nettoyage des données et analyse exploratoire"
format: html
editor: visual
---

# Importation des packages

```{r}
library(readr)
library(tseries)
library(corrplot)
```

# 1. Importation de la base et visualisation

```{r}
base <- read_csv("balanced_uk_md.csv")
View(base)
```

# 2. Modification de la base

```{r}
base <- base[-c(337,338),]
```

# 3. Analyse exploratoire

```{r}
str(base)
```

```{r}
colSums(is.na(base))
```

LIBOR_3mth 22 valeurs manquantes.

```{r}
base <- base[, !(names(base) == "LIBOR_3mth")]
```

# Vérification de la stationnarité

```{r}
adf.test(base$EMP_RATE)$p.value
```

0.01, p;value inf à 0.05 donc on rejette H0, la série est stationnaire.

```{r}
plot(base$Date, base$EMP_RATE, type = "l",
     main = "Graphique de la variable à expliquer stationnaire",
     xlab = "Années",
     ylab = "EMP_RATE")
```

# Stat descriptive

```{r}
summary(base$EMP_RATE)
var(base$EMP_RATE)
sd(base$EMP_RATE)
```

```{r}
boxplot(base$EMP_RATE)
```

# Corrélation entres les variables

```{r}
base_sans_date <- base[,-2]
```

```{r}
c <- cor(base_sans_date, method = "spearman")
corrplot(c, method = "color")
```

```{r}
dim(base_sans_date)
```

```{r}
M <- cor(base_sans_date, method = "spearman")

heatmap(M,
        Colv = TRUE,
        Rowv = TRUE,
        scale = "none")

```

```{r}
library(ggcorrplot)

M <- cor(base_sans_date, method = "spearman")

ggcorrplot(M,
           type = "lower",
           lab = FALSE,
           outline.col = "white")

```

```{r}
M <- cor(base_sans_date, method = "spearman")
M[lower.tri(M, diag = TRUE)] <- NA

library(reshape2)
df_corr <- melt(M, na.rm = TRUE)

top_corr <- df_corr[order(abs(df_corr$value), decreasing = TRUE), ]

head(top_corr, 30)   # les 30 plus fortes corrélations

```

```{r}
M <- cor(base_sans_date, method = "spearman")

threshold <- 0.5   # à ajuster selon ton besoin

M_filtered <- ifelse(abs(M) >= threshold, M, NA)

library(corrplot)
corrplot(M_filtered,
         method = "color",
         na.label = " ",
         tl.cex = 0.5)

```

```{r}
corrplot(M, method = "color",
         order = "hclust",     # regroupe les variables corrélées ensemble
         addrect = 6,          # dessine des rectangles autour des clusters
         tl.cex = 0.4)
```

```{r}
ggcorrplot(M, 
           hc.order = TRUE,      # tri par clustering
           type = "upper",       # seulement moitié supérieure
           tl.cex = 6,           # texte petit
           show.diag = FALSE)
```

